version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: urlshortener_postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: urlshortener_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
